.libPaths("~/biotools/Rlibs")
source("~/codes/cellRtools/main/functions.R")
library(Seurat)
library(Matrix)
library(dplyr)
library(tidyverse)
library(DropSeq.util)

zeisel.rank4.rfcv <- get(load("~/codes/test/RF/redo_rank4/zeisel.rank4.rfcv.RF_model_notImproved.Robj"))
zeisel.rank4.sub <- get(load("~/codes/test/RF/recursive/zeisel.rank4.sub.Rdata"))
traininData.mode4 <- trainPrep(model = zeisel.rank4.rfcv, modeSeurat=zeisel.rank4.sub, RankLabellist=c("TaxonomyRank1","TaxonomyRank2","TaxonomyRank3","TaxonomyRank4"))
zmode4 <- RecursiveTrainer(trainingData = traininData.mode4, run.name="z.modeL4")
